### ISSUE TITLE
Issues for RPK-Situations

### ISSUE THREAD

**Issue by tyras2** [OpenMeridian105/Meridian59#150]
As we talked about on IRC, a list of improvement to avoid excessively

- [ ] Add a possibilitie to increase the guardingangel after death to a longer time (For maybe 3-4 days).
- [x] Check the old logpen's if they're still working fine (Got to be enhancing each pen, no free for reds)
- [ ] Increase the strenght of a revenant. Also he should spawn more often.

Some more Idea's:

- [ ] Add maybe more time (slightly) for hunters to get an RPK by increase the phase time?

**Comment by skittles1** [comment]
> Add a possibilitie to increase the guardingangel after death to a longer time (For maybe 3-4 days).

For this one, a potential workaround for the timers is basing it on logged-in time (currently it expires whether the player stayed logged in for the 6 hours or not). Meaning the player could then get their full 6 hours of safe time, even if they didn't play it all at once.

> Check the old logpen's if they're still working fine (Got to be enhancing each pen, no free for reds)

I think some modifications are needed in the old system if we're going to use it, specifically making only cold-blood kills increase the pen, and capping it at some point so there's no char-destroying penalties. This way whites would pen the same as they do now, unsuccessful reds would be the same (or increase this linearly with each pen, resetting after 24hr of no pen) and reds with a lot of kills would be punished the most. Shield kills/mutual guild war kills wouldn't add to this pen (and nobody would have a free pen).

> Add maybe more time (slightly) for hunters to get an RPK by increase the phase time?

Not sure what you mean here, raise the amount of time before an innocent pens, or lower the amount before a murderer does?

**Comment by tyras2** [comment]
> For this one, a potential workaround for the timers is basing it on logged-in time (currently it expires whether the player stayed logged in for the 6 hours or not). Meaning the player could then get their full 6 hours of safe time, even if they didn't play it all at once.

Yes, that would be the best solution! Good idea

> I think some modifications are needed in the old system if we're going to use it, specifically making only cold-blood kills increase the pen, and capping it at some point so there's no char-destroying penalties. This way whites would pen the same as they do now, unsuccessful reds would be the same (or increase this linearly with each pen, resetting after 24hr of no pen) and reds with a lot of kills would be punished the most. Shield kills/mutual guild war kills wouldn't add to this pen (and nobody would have a free pen).

Agree! White pens should stay like they're, so they dont hide when they get the first pen, and keep fighting in guild/faction wars. Only would make a enhancing log pens for the reds. In fact, right now there is no incentive to hunt rpks.. and the rpks dont care about pens and start again and again

> Not sure what you mean here, raise the amount of time before an innocent pens, or lower the amount before a murderer does?

Often it happens that the time is too short to get ready to hunt an rpk if they got someone logged. Timer for innocent is 8min right now? Maybe raise to 10min?

**Comment by skittles1** [comment]
With the amount of settings and customisation available now for revenant speed, log penalties (and the ability to make penalties different for red/white), ghost time and temp safe, I think this issue can be put to rest for the time being.
